basePath: /
definitions:
  main.Categories:
    properties:
      name:
        type: string
    type: object
  main.Product:
    properties:
      categoriesRefs:
        items:
          type: string
        type: array
      dateTime:
        type: string
      name:
        type: string
      price:
        type: string
      sku:
        type: string
      weight:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: This is a sample shop service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Shop API
  version: "1.0"
paths:
  /categories:
    get:
      consumes:
      - application/json
      description: Get details of all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Categories'
            type: array
      summary: Get list of all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create new categories with the input payload
      parameters:
      - description: Create categories
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/main.Categories'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Categories'
      summary: Create a new categories
      tags:
      - categories
  /product:
    post:
      consumes:
      - application/json
      description: Create a new product with the input payload
      parameters:
      - description: Create product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Product'
      summary: Create a new product
      tags:
      - products
swagger: "2.0"
